/**
 * Adversarial tests for the triage classifier.
 * Generated by /test-fix-dev — creative probing phase.
 *
 * Tests boundary attacks, type confusion, injection payloads,
 * unicode stress, and semantic edge cases against classifyMaintenanceRequest.
 */
import { describe, it, expect } from "vitest";
import {
  classifyMaintenanceRequest,
  parseJsonFromText,
} from "@/lib/triage";
import type { AnthropicClient, ClassifyInput } from "@/lib/triage";

// --- Helpers ---

/** Mock client that always returns valid JSON regardless of input */
function createStableClient(): AnthropicClient {
  let callCount = 0;
  return {
    messages: {
      create: async () => {
        callCount++;
        if (callCount === 1) {
          return {
            content: [
              {
                type: "text",
                text: JSON.stringify({
                  self_resolvable: false,
                  troubleshooting_guide: null,
                  confidence: 0.8,
                }),
              },
            ],
          };
        }
        return {
          content: [
            {
              type: "text",
              text: JSON.stringify({
                category: "general",
                urgency: "low",
                recommended_action: "Inspect the issue.",
                cost_estimate_low: 50,
                cost_estimate_high: 200,
                confidence_score: 0.7,
              }),
            },
          ],
        };
      },
    },
  };
}

/** Mock client that echoes the input back so we can inspect what was sent */
function createEchoClient(): {
  client: AnthropicClient;
  getCalls: () => { model: string; messages: unknown[] }[];
} {
  const calls: { model: string; messages: unknown[] }[] = [];
  let callCount = 0;
  const client: AnthropicClient = {
    messages: {
      create: async (params) => {
        calls.push({ model: params.model, messages: params.messages });
        callCount++;
        if (callCount === 1) {
          return {
            content: [
              {
                type: "text",
                text: '{"self_resolvable": false, "troubleshooting_guide": null, "confidence": 0.5}',
              },
            ],
          };
        }
        return {
          content: [
            {
              type: "text",
              text: '{"category": "general", "urgency": "low", "recommended_action": "inspect", "cost_estimate_low": 0, "cost_estimate_high": 0, "confidence_score": 0.5}',
            },
          ],
        };
      },
    },
  };
  return { client, getCalls: () => calls };
}

// =============================================================================
// BOUNDARY ATTACKS
// =============================================================================

describe("Boundary attacks on classifyMaintenanceRequest", () => {
  it("handles empty string input", async () => {
    const client = createStableClient();
    const input: ClassifyInput = { tenant_message: "" };
    const result = await classifyMaintenanceRequest(input, client);
    expect(result).toBeDefined();
    expect(result.gatekeeper).toBeDefined();
    expect(result.classification).toBeDefined();
  });

  it("handles 10,000 character input without crashing", async () => {
    const client = createStableClient();
    const longMessage = "My sink is leaking. ".repeat(500); // ~10k chars
    const input: ClassifyInput = { tenant_message: longMessage };
    const result = await classifyMaintenanceRequest(input, client);
    expect(result.classification).toBeDefined();
    expect(result.classification.category).toBeTruthy();
  });

  it("handles single character input", async () => {
    const client = createStableClient();
    const input: ClassifyInput = { tenant_message: "." };
    const result = await classifyMaintenanceRequest(input, client);
    expect(result.classification).toBeDefined();
  });

  it("handles whitespace-only input", async () => {
    const client = createStableClient();
    const input: ClassifyInput = { tenant_message: "   \t\n  " };
    const result = await classifyMaintenanceRequest(input, client);
    expect(result.classification).toBeDefined();
  });

  it("handles empty photos array", async () => {
    const client = createStableClient();
    const input: ClassifyInput = { tenant_message: "leak", photos: [] };
    const result = await classifyMaintenanceRequest(input, client);
    expect(result.classification).toBeDefined();
  });

  it("handles more than 5 photos (should only send first 5)", async () => {
    const { client, getCalls } = createEchoClient();
    const photos = Array.from({ length: 8 }, (_, i) => ({
      base64: `photo_data_${i}`,
      media_type: "image/jpeg" as const,
    }));
    const input: ClassifyInput = { tenant_message: "damage", photos };
    await classifyMaintenanceRequest(input, client);

    // The estimator call (second one) should have at most 6 content blocks (1 text + 5 images)
    const estimatorCall = getCalls()[1];
    const content = (estimatorCall.messages[0] as { content: unknown[] }).content;
    const imageBlocks = (content as { type: string }[]).filter(
      (b) => b.type === "image"
    );
    expect(imageBlocks.length).toBeLessThanOrEqual(5);
  });
});

// =============================================================================
// INJECTION TESTING
// =============================================================================

describe("Injection payloads in tenant_message", () => {
  it("handles SQL injection attempt", async () => {
    const client = createStableClient();
    const input: ClassifyInput = {
      tenant_message: "'; DROP TABLE properties; --",
    };
    const result = await classifyMaintenanceRequest(input, client);
    // Should not crash — the classifier just passes text to the LLM
    expect(result.classification).toBeDefined();
  });

  it("handles XSS payload", async () => {
    const client = createStableClient();
    const input: ClassifyInput = {
      tenant_message: '<script>alert("xss")</script> My sink is broken',
    };
    const result = await classifyMaintenanceRequest(input, client);
    expect(result.classification).toBeDefined();
  });

  it("handles path traversal in message", async () => {
    const client = createStableClient();
    const input: ClassifyInput = {
      tenant_message: "../../etc/passwd",
    };
    const result = await classifyMaintenanceRequest(input, client);
    expect(result.classification).toBeDefined();
  });

  it("handles command injection attempt", async () => {
    const client = createStableClient();
    const input: ClassifyInput = {
      tenant_message: "; rm -rf / ; echo broken pipe",
    };
    const result = await classifyMaintenanceRequest(input, client);
    expect(result.classification).toBeDefined();
  });

  it("handles template injection", async () => {
    const client = createStableClient();
    const input: ClassifyInput = {
      tenant_message: "{{7*7}} ${process.env.SECRET} broken faucet",
    };
    const result = await classifyMaintenanceRequest(input, client);
    expect(result.classification).toBeDefined();
  });

  it("passes injection payloads through to LLM as-is (no sanitization needed at this layer)", async () => {
    const { client, getCalls } = createEchoClient();
    const xssPayload = '<img onerror=alert(1) src=x> broken heater';
    await classifyMaintenanceRequest({ tenant_message: xssPayload }, client);

    // Both the gatekeeper and estimator should receive the original message
    const gatekeeperCall = getCalls()[0];
    const gatekeeperMsg = (gatekeeperCall.messages[0] as { content: string }).content;
    expect(gatekeeperMsg).toContain(xssPayload);
  });
});

// =============================================================================
// UNICODE STRESS
// =============================================================================

describe("Unicode stress on classifyMaintenanceRequest", () => {
  it("handles emoji-heavy input", async () => {
    const client = createStableClient();
    const emojiMessage = "🔥💧⚡🏠🔧".repeat(100);
    const input: ClassifyInput = { tenant_message: emojiMessage };
    const result = await classifyMaintenanceRequest(input, client);
    expect(result.classification).toBeDefined();
  });

  it("handles RTL text", async () => {
    const client = createStableClient();
    const input: ClassifyInput = {
      tenant_message: "\u200Fالصنبور مكسور والماء يتسرب",
    };
    const result = await classifyMaintenanceRequest(input, client);
    expect(result.classification).toBeDefined();
  });

  it("handles null bytes in message", async () => {
    const client = createStableClient();
    const input: ClassifyInput = {
      tenant_message: "broken\x00pipe\x00leaking",
    };
    const result = await classifyMaintenanceRequest(input, client);
    expect(result.classification).toBeDefined();
  });

  it("handles zero-width joiners", async () => {
    const client = createStableClient();
    const input: ClassifyInput = {
      tenant_message: "b\u200Dr\u200Do\u200Dk\u200De\u200Dn pipe",
    };
    const result = await classifyMaintenanceRequest(input, client);
    expect(result.classification).toBeDefined();
  });

  it("handles mixed scripts (Arabic + Chinese + Cyrillic)", async () => {
    const client = createStableClient();
    const input: ClassifyInput = {
      tenant_message: "مكسور 坏了 сломано broken pipe",
    };
    const result = await classifyMaintenanceRequest(input, client);
    expect(result.classification).toBeDefined();
  });

  it("handles emoji-only message", async () => {
    const client = createStableClient();
    const input: ClassifyInput = { tenant_message: "🔥🔥🔥🔥🔥" };
    const result = await classifyMaintenanceRequest(input, client);
    expect(result.classification).toBeDefined();
  });
});

// =============================================================================
// SEMANTIC EDGE CASES
// =============================================================================

describe("Semantic edge cases on classifyMaintenanceRequest", () => {
  it("handles code snippet as maintenance message", async () => {
    const client = createStableClient();
    const input: ClassifyInput = {
      tenant_message:
        "function exploit() { return db.query('SELECT * FROM users') }",
    };
    const result = await classifyMaintenanceRequest(input, client);
    expect(result.classification).toBeDefined();
  });

  it("handles mixed category signals", async () => {
    const client = createStableClient();
    const input: ClassifyInput = {
      tenant_message:
        "My toilet is on fire and there are rats in the electrical wiring and the ceiling is caving in",
    };
    const result = await classifyMaintenanceRequest(input, client);
    expect(result.classification).toBeDefined();
    expect(result.classification.category).toBeTruthy();
  });

  it("handles non-maintenance content", async () => {
    const client = createStableClient();
    const input: ClassifyInput = {
      tenant_message: "What's the weather like today? I love pizza.",
    };
    const result = await classifyMaintenanceRequest(input, client);
    expect(result.classification).toBeDefined();
  });

  it("handles duplicate rapid calls (concurrency)", async () => {
    const client = createStableClient();
    const input: ClassifyInput = { tenant_message: "Leaky faucet" };

    // Fire 5 concurrent requests
    const results = await Promise.all([
      classifyMaintenanceRequest(input, createStableClient()),
      classifyMaintenanceRequest(input, createStableClient()),
      classifyMaintenanceRequest(input, createStableClient()),
      classifyMaintenanceRequest(input, createStableClient()),
      classifyMaintenanceRequest(input, createStableClient()),
    ]);

    // All should succeed
    for (const result of results) {
      expect(result.classification).toBeDefined();
      expect(result.gatekeeper).toBeDefined();
    }
  });
});

// =============================================================================
// parseJsonFromText ADVERSARIAL
// =============================================================================

describe("parseJsonFromText adversarial inputs", () => {
  it("handles JSON with trailing comma (should throw)", () => {
    expect(() => parseJsonFromText('{"key": "value",}')).toThrow();
  });

  it("handles nested code fences (extracts between first pair, inner fences corrupt JSON)", () => {
    const input = '```json\n```json\n{"key": "value"}\n```\n```';
    // Regex captures between first ``` and next ``` — inner ```json corrupts the JSON
    expect(() => parseJsonFromText(input)).toThrow();
  });

  it("handles extremely deeply nested JSON", () => {
    let json = '{"a":';
    for (let i = 0; i < 50; i++) json += '{"a":';
    json += '"end"';
    for (let i = 0; i < 51; i++) json += "}";
    const result = parseJsonFromText(json);
    expect(result).toBeDefined();
  });

  it("handles JSON with unicode escapes", () => {
    const result = parseJsonFromText('{"msg": "\\u0048ello"}');
    expect(result).toEqual({ msg: "Hello" });
  });

  it("handles empty string (should throw)", () => {
    expect(() => parseJsonFromText("")).toThrow();
  });

  it("handles JSON with only whitespace inside fences", () => {
    expect(() => parseJsonFromText("```json\n   \n```")).toThrow();
  });
});

// =============================================================================
// LLM RESPONSE EDGE CASES
// =============================================================================

describe("Malformed LLM response handling", () => {
  it("handles LLM returning non-JSON text", async () => {
    const client: AnthropicClient = {
      messages: {
        create: async () => ({
          content: [{ type: "text", text: "I cannot classify this request." }],
        }),
      },
    };

    const result = await classifyMaintenanceRequest(
      { tenant_message: "broken pipe" },
      client
    );

    // Should fall back to defaults since JSON parsing fails
    expect(result.gatekeeper).toBeDefined();
    expect(result.classification).toBeDefined();
  });

  it("handles LLM returning empty content array", async () => {
    const client: AnthropicClient = {
      messages: {
        create: async () => ({
          content: [],
        }),
      },
    };

    // This should trigger a catch and fall back to defaults
    await expect(async () => {
      await classifyMaintenanceRequest({ tenant_message: "test" }, client);
    }).not.toThrow();
  });

  it("handles LLM returning content with wrong type", async () => {
    const client: AnthropicClient = {
      messages: {
        create: async () => ({
          content: [{ type: "tool_use", text: undefined }],
        }),
      },
    };

    // content[0].type !== "text" → falls back to "{}" → parsed to empty obj
    // gatekeeper and estimator should still return (possibly with defaults)
    const result = await classifyMaintenanceRequest(
      { tenant_message: "test" },
      client
    );
    expect(result).toBeDefined();
  });

  it("handles LLM returning partial JSON", async () => {
    let callCount = 0;
    const client: AnthropicClient = {
      messages: {
        create: async () => {
          callCount++;
          if (callCount === 1) {
            return {
              content: [
                {
                  type: "text",
                  text: '{"self_resolvable": true, "troubleshoot',
                },
              ],
            };
          }
          return {
            content: [
              {
                type: "text",
                text: '{"category": "plumbing", "urgency": "low", "recommended_action": "fix", "cost_estimate_low": 0, "cost_estimate_high": 0, "confidence_score": 0.5}',
              },
            ],
          };
        },
      },
    };

    // Partial JSON in gatekeeper → falls to defaults, estimator should still work
    const result = await classifyMaintenanceRequest(
      { tenant_message: "drip" },
      client
    );
    expect(result.gatekeeper.self_resolvable).toBe(false); // default
    expect(result.classification.category).toBe("plumbing");
  });

  it("handles LLM returning extra fields (should not crash)", async () => {
    const client: AnthropicClient = {
      messages: {
        create: async () => ({
          content: [
            {
              type: "text",
              text: JSON.stringify({
                self_resolvable: false,
                troubleshooting_guide: null,
                confidence: 0.9,
                extra_field: "unexpected",
                nested: { deep: true },
              }),
            },
          ],
        }),
      },
    };

    const result = await classifyMaintenanceRequest(
      { tenant_message: "leak" },
      client
    );
    expect(result.gatekeeper.confidence).toBe(0.9);
  });
});
