/**
 * Adversarial tests for Test Lab API routes.
 * Generated by /test-fix-dev — creative probing phase.
 *
 * Probes boundary attacks, injection, auth bypasses, and type confusion
 * against the Test Lab API endpoints.
 */
import { describe, it, expect, vi, beforeEach } from "vitest";
import {
  resetAllMocks,
  setMockAuth,
  setMockRole,
  setSupabaseResults,
  buildRequest,
  mockAuth,
  mockCreateServerSupabaseClient,
} from "../helpers";

vi.mock("@clerk/nextjs/server", () => ({
  auth: () => mockAuth(),
}));

vi.mock("@/lib/supabase/server", () => ({
  createServerSupabaseClient: () => mockCreateServerSupabaseClient(),
}));

vi.mock("@/lib/anthropic", () => ({
  anthropic: {
    messages: {
      create: vi.fn().mockResolvedValue({
        content: [
          {
            type: "text",
            text: JSON.stringify({
              self_resolvable: false,
              troubleshooting_guide: null,
              confidence: 0.8,
            }),
          },
        ],
      }),
    },
  },
}));

vi.mock("@/lib/triage", () => ({
  classifyMaintenanceRequest: vi.fn().mockResolvedValue({
    gatekeeper: {
      self_resolvable: false,
      troubleshooting_guide: null,
      confidence: 0.8,
    },
    classification: {
      category: "general",
      urgency: "low",
      recommended_action: "Inspect",
      cost_estimate_low: 0,
      cost_estimate_high: 0,
      confidence_score: 0.7,
    },
  }),
}));

describe("Test Lab API — Adversarial", () => {
  beforeEach(() => resetAllMocks());

  // =========================================================================
  // AUTH PROBING
  // =========================================================================

  describe("Auth probing", () => {
    it("GET /api/test-lab/runs returns 401 without auth", async () => {
      setMockAuth(null);
      const { GET } = await import("@/app/api/test-lab/runs/route");
      const res = await GET(buildRequest("/api/test-lab/runs"));
      expect(res.status).toBe(401);
    });

    it("POST /api/test-lab/runs returns 401 without auth", async () => {
      setMockAuth(null);
      const { POST } = await import("@/app/api/test-lab/runs/route");
      const res = await POST(
        buildRequest("/api/test-lab/runs", {
          method: "POST",
          body: { component_name: "triage" },
        })
      );
      expect(res.status).toBe(401);
    });

    it("GET /api/test-lab/runs/[id] returns 401 without auth", async () => {
      setMockAuth(null);
      const { GET } = await import("@/app/api/test-lab/runs/[id]/route");
      const res = await GET(buildRequest("/api/test-lab/runs/abc"), {
        params: Promise.resolve({ id: "abc" }),
      });
      expect(res.status).toBe(401);
    });

    it("POST /api/test-lab/components/triage/manual returns 401 without auth", async () => {
      setMockAuth(null);
      const { POST } = await import(
        "@/app/api/test-lab/components/triage/manual/route"
      );
      const res = await POST(
        buildRequest("/api/test-lab/components/triage/manual", {
          method: "POST",
          body: { message: "test" },
        })
      );
      expect(res.status).toBe(401);
    });
  });

  // =========================================================================
  // POST /api/test-lab/runs — BOUNDARY ATTACKS
  // =========================================================================

  describe("POST /api/test-lab/runs — boundary attacks", () => {
    it("rejects empty body", async () => {
      const { POST } = await import("@/app/api/test-lab/runs/route");
      const res = await POST(
        buildRequest("/api/test-lab/runs", { method: "POST", body: {} })
      );
      expect(res.status).toBe(400);
    });

    it("rejects null component_name", async () => {
      const { POST } = await import("@/app/api/test-lab/runs/route");
      const res = await POST(
        buildRequest("/api/test-lab/runs", {
          method: "POST",
          body: { component_name: null },
        })
      );
      expect(res.status).toBe(400);
    });

    it("rejects empty string component_name", async () => {
      const { POST } = await import("@/app/api/test-lab/runs/route");
      const res = await POST(
        buildRequest("/api/test-lab/runs", {
          method: "POST",
          body: { component_name: "" },
        })
      );
      expect(res.status).toBe(400);
    });

    it("rejects array as component_name", async () => {
      const { POST } = await import("@/app/api/test-lab/runs/route");
      const res = await POST(
        buildRequest("/api/test-lab/runs", {
          method: "POST",
          body: { component_name: ["triage", "other"] },
        })
      );
      expect(res.status).toBe(400);
    });

    it("rejects number as component_name", async () => {
      const { POST } = await import("@/app/api/test-lab/runs/route");
      const res = await POST(
        buildRequest("/api/test-lab/runs", {
          method: "POST",
          body: { component_name: 12345 },
        })
      );
      expect(res.status).toBe(400);
    });

    it("handles SQL injection in component_name", async () => {
      setSupabaseResults([
        { data: { id: "run-1", component_name: "'; DROP TABLE--" }, error: null },
      ]);
      const { POST } = await import("@/app/api/test-lab/runs/route");
      const res = await POST(
        buildRequest("/api/test-lab/runs", {
          method: "POST",
          body: { component_name: "'; DROP TABLE test_runs; --" },
        })
      );
      // Should not crash — Supabase parameterizes queries
      expect([201, 400, 500]).toContain(res.status);
    });

    it("handles XSS in component_name", async () => {
      setSupabaseResults([
        {
          data: { id: "run-1", component_name: '<script>alert(1)</script>' },
          error: null,
        },
      ]);
      const { POST } = await import("@/app/api/test-lab/runs/route");
      const res = await POST(
        buildRequest("/api/test-lab/runs", {
          method: "POST",
          body: { component_name: '<script>alert(1)</script>' },
        })
      );
      // Accepted — no server-side validation on component_name content
      // This is a finding if the value is stored and rendered unescaped
      expect([201, 400]).toContain(res.status);
    });
  });

  // =========================================================================
  // POST /api/test-lab/components/triage/manual — ADVERSARIAL INPUTS
  // =========================================================================

  describe("POST /api/test-lab/components/triage/manual — adversarial", () => {
    it("rejects empty message", async () => {
      const { POST } = await import(
        "@/app/api/test-lab/components/triage/manual/route"
      );
      const res = await POST(
        buildRequest("/api/test-lab/components/triage/manual", {
          method: "POST",
          body: { message: "" },
        })
      );
      expect(res.status).toBe(400);
    });

    it("rejects whitespace-only message", async () => {
      const { POST } = await import(
        "@/app/api/test-lab/components/triage/manual/route"
      );
      const res = await POST(
        buildRequest("/api/test-lab/components/triage/manual", {
          method: "POST",
          body: { message: "   \t\n  " },
        })
      );
      expect(res.status).toBe(400);
    });

    it("rejects null message", async () => {
      const { POST } = await import(
        "@/app/api/test-lab/components/triage/manual/route"
      );
      const res = await POST(
        buildRequest("/api/test-lab/components/triage/manual", {
          method: "POST",
          body: { message: null },
        })
      );
      expect(res.status).toBe(400);
    });

    it("rejects number as message", async () => {
      const { POST } = await import(
        "@/app/api/test-lab/components/triage/manual/route"
      );
      const res = await POST(
        buildRequest("/api/test-lab/components/triage/manual", {
          method: "POST",
          body: { message: 12345 },
        })
      );
      expect(res.status).toBe(400);
    });

    it("rejects boolean as message", async () => {
      const { POST } = await import(
        "@/app/api/test-lab/components/triage/manual/route"
      );
      const res = await POST(
        buildRequest("/api/test-lab/components/triage/manual", {
          method: "POST",
          body: { message: true },
        })
      );
      expect(res.status).toBe(400);
    });

    it("handles 10,000 character message", async () => {
      const { POST } = await import(
        "@/app/api/test-lab/components/triage/manual/route"
      );
      const longMessage = "A".repeat(10000);
      const res = await POST(
        buildRequest("/api/test-lab/components/triage/manual", {
          method: "POST",
          body: { message: longMessage },
        })
      );
      // Should still work — no length limit currently
      expect(res.status).toBe(200);
    });

    it("handles SQL injection in message", async () => {
      const { POST } = await import(
        "@/app/api/test-lab/components/triage/manual/route"
      );
      const res = await POST(
        buildRequest("/api/test-lab/components/triage/manual", {
          method: "POST",
          body: { message: "'; DROP TABLE test_runs; --" },
        })
      );
      expect(res.status).toBe(200);
    });

    it("handles XSS in message", async () => {
      const { POST } = await import(
        "@/app/api/test-lab/components/triage/manual/route"
      );
      const res = await POST(
        buildRequest("/api/test-lab/components/triage/manual", {
          method: "POST",
          body: { message: '<script>alert("xss")</script> my pipe is broken' },
        })
      );
      expect(res.status).toBe(200);
    });

    it("handles emoji-only message", async () => {
      const { POST } = await import(
        "@/app/api/test-lab/components/triage/manual/route"
      );
      const res = await POST(
        buildRequest("/api/test-lab/components/triage/manual", {
          method: "POST",
          body: { message: "🔥🔥🔥🔥🔥" },
        })
      );
      expect(res.status).toBe(200);
    });

    it("handles non-English text (Spanish)", async () => {
      const { POST } = await import(
        "@/app/api/test-lab/components/triage/manual/route"
      );
      const res = await POST(
        buildRequest("/api/test-lab/components/triage/manual", {
          method: "POST",
          body: { message: "El grifo de la cocina está goteando mucho agua" },
        })
      );
      expect(res.status).toBe(200);
    });

    it("handles non-English text (Japanese)", async () => {
      const { POST } = await import(
        "@/app/api/test-lab/components/triage/manual/route"
      );
      const res = await POST(
        buildRequest("/api/test-lab/components/triage/manual", {
          method: "POST",
          body: { message: "台所の蛇口が水漏れしています" },
        })
      );
      expect(res.status).toBe(200);
    });

    it("handles non-English text (Arabic)", async () => {
      const { POST } = await import(
        "@/app/api/test-lab/components/triage/manual/route"
      );
      const res = await POST(
        buildRequest("/api/test-lab/components/triage/manual", {
          method: "POST",
          body: { message: "الصنبور في المطبخ يسرب الماء بشكل كبير" },
        })
      );
      expect(res.status).toBe(200);
    });

    it("handles code snippet as message", async () => {
      const { POST } = await import(
        "@/app/api/test-lab/components/triage/manual/route"
      );
      const res = await POST(
        buildRequest("/api/test-lab/components/triage/manual", {
          method: "POST",
          body: {
            message:
              "function exploit() { return db.query('SELECT * FROM users') }",
          },
        })
      );
      expect(res.status).toBe(200);
    });

    it("handles mixed category signals", async () => {
      const { POST } = await import(
        "@/app/api/test-lab/components/triage/manual/route"
      );
      const res = await POST(
        buildRequest("/api/test-lab/components/triage/manual", {
          method: "POST",
          body: {
            message:
              "My toilet is on fire and there are rats in the wiring and the ceiling is caving in",
          },
        })
      );
      expect(res.status).toBe(200);
      const body = await res.json();
      expect(body.classification).toBeDefined();
    });

    it("rejects object as message", async () => {
      const { POST } = await import(
        "@/app/api/test-lab/components/triage/manual/route"
      );
      const res = await POST(
        buildRequest("/api/test-lab/components/triage/manual", {
          method: "POST",
          body: { message: { nested: "object" } },
        })
      );
      expect(res.status).toBe(400);
    });

    it("rejects array as message", async () => {
      const { POST } = await import(
        "@/app/api/test-lab/components/triage/manual/route"
      );
      const res = await POST(
        buildRequest("/api/test-lab/components/triage/manual", {
          method: "POST",
          body: { message: ["hello", "world"] },
        })
      );
      expect(res.status).toBe(400);
    });

    it("handles null bytes in message", async () => {
      const { POST } = await import(
        "@/app/api/test-lab/components/triage/manual/route"
      );
      const res = await POST(
        buildRequest("/api/test-lab/components/triage/manual", {
          method: "POST",
          body: { message: "broken\x00pipe" },
        })
      );
      expect(res.status).toBe(200);
    });

    it("handles template injection in message", async () => {
      const { POST } = await import(
        "@/app/api/test-lab/components/triage/manual/route"
      );
      const res = await POST(
        buildRequest("/api/test-lab/components/triage/manual", {
          method: "POST",
          body: { message: "{{7*7}} ${process.env.SECRET}" },
        })
      );
      expect(res.status).toBe(200);
    });

    it("handles extra unknown fields in body", async () => {
      const { POST } = await import(
        "@/app/api/test-lab/components/triage/manual/route"
      );
      const res = await POST(
        buildRequest("/api/test-lab/components/triage/manual", {
          method: "POST",
          body: {
            message: "leaky faucet",
            admin: true,
            role: "admin",
            __proto__: { isAdmin: true },
          },
        })
      );
      // Should ignore extra fields and process normally
      expect(res.status).toBe(200);
    });
  });

  // =========================================================================
  // GET /api/test-lab/runs — QUERY PARAM PROBING
  // =========================================================================

  describe("GET /api/test-lab/runs — query param probing", () => {
    it("handles negative limit", async () => {
      setSupabaseResults([{ data: [], error: null }]);
      const { GET } = await import("@/app/api/test-lab/runs/route");
      const res = await GET(
        buildRequest("/api/test-lab/runs?limit=-1")
      );
      // Math.min(-1, 100) = -1 — may cause Supabase error or empty results
      expect([200, 400, 500]).toContain(res.status);
    });

    it("handles zero limit", async () => {
      setSupabaseResults([{ data: [], error: null }]);
      const { GET } = await import("@/app/api/test-lab/runs/route");
      const res = await GET(buildRequest("/api/test-lab/runs?limit=0"));
      expect([200, 400]).toContain(res.status);
    });

    it("handles limit=999999 (capped to 100)", async () => {
      setSupabaseResults([{ data: [], error: null }]);
      const { GET } = await import("@/app/api/test-lab/runs/route");
      const res = await GET(
        buildRequest("/api/test-lab/runs?limit=999999")
      );
      expect(res.status).toBe(200);
    });

    it("handles NaN limit", async () => {
      setSupabaseResults([{ data: [], error: null }]);
      const { GET } = await import("@/app/api/test-lab/runs/route");
      const res = await GET(
        buildRequest("/api/test-lab/runs?limit=notanumber")
      );
      // parseInt("notanumber") = NaN, Math.min(NaN, 100) = NaN
      expect([200, 400, 500]).toContain(res.status);
    });

    it("handles SQL injection in component param", async () => {
      setSupabaseResults([{ data: [], error: null }]);
      const { GET } = await import("@/app/api/test-lab/runs/route");
      const res = await GET(
        buildRequest(
          "/api/test-lab/runs?component=triage%27%3B%20DROP%20TABLE%20test_runs%3B--"
        )
      );
      // Supabase parameterizes — should not crash
      expect([200, 400, 500]).toContain(res.status);
    });
  });

  // =========================================================================
  // GET /api/test-lab/runs/[id] — ID PROBING
  // =========================================================================

  describe("GET /api/test-lab/runs/[id] — ID probing", () => {
    it("handles empty string ID", async () => {
      setSupabaseResults([{ data: null, error: { code: "PGRST116" } }]);
      const { GET } = await import("@/app/api/test-lab/runs/[id]/route");
      const res = await GET(buildRequest("/api/test-lab/runs/"), {
        params: Promise.resolve({ id: "" }),
      });
      expect([400, 404, 500]).toContain(res.status);
    });

    it("handles SQL injection in ID", async () => {
      setSupabaseResults([{ data: null, error: { code: "PGRST116" } }]);
      const { GET } = await import("@/app/api/test-lab/runs/[id]/route");
      const res = await GET(
        buildRequest("/api/test-lab/runs/'; DROP TABLE--"),
        {
          params: Promise.resolve({ id: "'; DROP TABLE test_runs; --" }),
        }
      );
      expect([400, 404, 500]).toContain(res.status);
    });

    it("handles path traversal in ID", async () => {
      setSupabaseResults([{ data: null, error: { code: "PGRST116" } }]);
      const { GET } = await import("@/app/api/test-lab/runs/[id]/route");
      const res = await GET(
        buildRequest("/api/test-lab/runs/../../etc/passwd"),
        {
          params: Promise.resolve({ id: "../../etc/passwd" }),
        }
      );
      expect([400, 404, 500]).toContain(res.status);
    });

    it("handles extremely long ID", async () => {
      const longId = "a".repeat(10000);
      setSupabaseResults([{ data: null, error: { code: "PGRST116" } }]);
      const { GET } = await import("@/app/api/test-lab/runs/[id]/route");
      const res = await GET(
        buildRequest(`/api/test-lab/runs/${longId}`),
        {
          params: Promise.resolve({ id: longId }),
        }
      );
      expect([400, 404, 500]).toContain(res.status);
    });
  });
});
